server:
  port: 8888
spring:
  data:
    cassandra:
      keyspace-name: reactive
      port: 9042
      schema-action: create_if_not_exists
      contact-points:
        - localhost
# actuator config
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always